version: '3.8'
services:
  yftools-md2html-backend:
    build: ./backend
    container_name: yftools-md2html-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/configs/config.yaml:/app/configs/config.yaml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  yftools-md2html-frontend:
    build: ./webapp
    container_name: yftools-md2html-frontend
    ports:
      - "3000:80"
    depends_on:
      - yftools-md2html-backend
    restart: unless-stopped
